// <auto-generated />
namespace bimestre4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SecondCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201411221858283_SecondCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
